export const STOCK_BATCH_STATUS = {
  SELLABLE: 1,
  PENDING_INSPECTION: 2,
  UNSELLABLE: 3,
} as const;

export const STOCK_BATCH_STATUS_VALUES = [
  STOCK_BATCH_STATUS.SELLABLE,
  STOCK_BATCH_STATUS.PENDING_INSPECTION,
  STOCK_BATCH_STATUS.UNSELLABLE,
] as const;

export type StockBatchStatusValue = (typeof STOCK_BATCH_STATUS_VALUES)[number];
