export const AI_CAPABILITY_CODES = {
  OK: 'OK',
  AI_PROVIDER_MISSING: 'AI_PROVIDER_MISSING',
  AI_AUTH_KEY_MISSING: 'AI_AUTH_KEY_MISSING',
  AI_MODEL_API_KEY_MISSING: 'AI_MODEL_API_KEY_MISSING',
  SERVICE_ID_MISSING: 'SERVICE_ID_MISSING',
  PROMPT_SERVICE_URL_MISSING: 'PROMPT_SERVICE_URL_MISSING',
  PROMPT_SERVICE_UNAVAILABLE: 'PROMPT_SERVICE_UNAVAILABLE',
  PROMPT_SERVICE_REQUEST_FAILED: 'PROMPT_SERVICE_REQUEST_FAILED',
  PROMPT_RESPONSE_INVALID: 'PROMPT_RESPONSE_INVALID',
  INDUSTRY_MISMATCH: 'INDUSTRY_MISMATCH',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_DISABLED: 'API_KEY_DISABLED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  LICENSE_UNBOUND: 'LICENSE_UNBOUND',
  SERVICE_ID_REQUIRED: 'SERVICE_ID_REQUIRED',
  SERVICE_ID_MISMATCH: 'SERVICE_ID_MISMATCH',
  SERVICE_ALREADY_BOUND: 'SERVICE_ALREADY_BOUND',
  INSTANCE_LEASE_CONFLICT: 'INSTANCE_LEASE_CONFLICT',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  PROVIDER_NOT_SUPPORTED: 'PROVIDER_NOT_SUPPORTED',
  ATTACHMENT_INVALID: 'ATTACHMENT_INVALID',
  MODEL_RESPONSE_INVALID: 'MODEL_RESPONSE_INVALID',
  MODEL_RESULT_INVALID: 'MODEL_RESULT_INVALID',
  MODEL_INVOKE_FAILED: 'MODEL_INVOKE_FAILED',
  AI_RUNTIME_ERROR: 'AI_RUNTIME_ERROR',
  AI_INTERNAL_ERROR: 'AI_INTERNAL_ERROR',
} as const

export type AiCapabilityCode = typeof AI_CAPABILITY_CODES[keyof typeof AI_CAPABILITY_CODES]

export const AI_KEY_INVALID_CODES: AiCapabilityCode[] = [
  AI_CAPABILITY_CODES.API_KEY_NOT_FOUND,
  AI_CAPABILITY_CODES.API_KEY_DISABLED,
  AI_CAPABILITY_CODES.API_KEY_EXPIRED,
]

export const AI_BINDING_ERROR_CODES: AiCapabilityCode[] = [
  AI_CAPABILITY_CODES.LICENSE_UNBOUND,
  AI_CAPABILITY_CODES.SERVICE_ID_MISMATCH,
  AI_CAPABILITY_CODES.SERVICE_ALREADY_BOUND,
  AI_CAPABILITY_CODES.INSTANCE_LEASE_CONFLICT,
]

export const AI_LOCAL_CONFIG_MISSING_CODES: AiCapabilityCode[] = [
  AI_CAPABILITY_CODES.AI_PROVIDER_MISSING,
  AI_CAPABILITY_CODES.AI_AUTH_KEY_MISSING,
  AI_CAPABILITY_CODES.AI_MODEL_API_KEY_MISSING,
  AI_CAPABILITY_CODES.SERVICE_ID_MISSING,
  AI_CAPABILITY_CODES.PROMPT_SERVICE_URL_MISSING,
]

export function isAiCapabilityCode(code?: string): code is AiCapabilityCode {
  return Boolean(code && Object.values(AI_CAPABILITY_CODES).includes(code as AiCapabilityCode))
}
